{% set name = "pystac-client" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pystac-client-{{ version }}.tar.gz
  sha256: 8e014f669a88d55c7902a9c1a839048ee87939576060b2d3cc9f6d17cf879056

build:
  number: 0
  noarch: python
  entry_points:
    - stac-client=pystac_client.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pystac >=1.4.0
    - python-dateutil >=2.7.0
    - requests >=2.25

test:
  imports:
    - pystac_client
  commands:
    - pip check
    - stac-client --help
  requires:
    - pip

about:
  home: https://github.com/stac-utils/pystac-client.git
  summary: Python library for working with Spatiotemporal Asset Catalog (STAC).
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matthewhanson
    - ocefpaf
