{% set name = "pystac-client" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pystac-client-{{ version }}.tar.gz
  sha256: 823bc9489e6074b4c4a77064195847eb486c35123076204104be4af4ec03c81b

build:
  number: 0
  noarch: python
  entry_points:
    - stac-client=pystac_client.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests >=2.28.2
    - pystac >=1.7.2
    - python-dateutil >=2.8.2

test:
  imports:
    - pystac_client
  commands:
    - pip check
    - stac-client --help
  requires:
    - pip

about:
  home: https://github.com/stac-utils/pystac-client.git
  summary: Python library for working with Spatiotemporal Asset Catalog (STAC).
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matthewhanson
    - ocefpaf
