{% set name = "pystac-client" %}
{% set version = "0.7.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pystac-client-{{ version }}.tar.gz
  sha256: fd37351410f18545398bd53c3349bf28dbd8f98ad2bddc71bb840bf873b01e36

build:
  number: 0
  noarch: python
  entry_points:
    - stac-client=pystac_client.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - requests >=2.28.2
    - pystac >=1.8.2
    - python-dateutil >=2.8.2

test:
  imports:
    - pystac_client
  commands:
    - pip check
    - stac-client --help
  requires:
    - pip

about:
  home: https://github.com/stac-utils/pystac-client.git
  summary: Python library for working with Spatiotemporal Asset Catalog (STAC).
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matthewhanson
    - ocefpaf
